# tqdm 이쁘게쓰기

In [1]:
from tqdm.auto import tqdm, trange
from time import sleep
 
for i in trange(10, desc='1st loop'):
    for j in tqdm(range(100), desc='2nd loop'):
        sleep(0.01)

Widget Javascript not detected.  It may not be installed or enabled properly.


Widget Javascript not detected.  It may not be installed or enabled properly.


Widget Javascript not detected.  It may not be installed or enabled properly.


Widget Javascript not detected.  It may not be installed or enabled properly.


Widget Javascript not detected.  It may not be installed or enabled properly.


Widget Javascript not detected.  It may not be installed or enabled properly.


KeyboardInterrupt: 

In [1]:
import torch
import random
import torch.backends.cudnn as cudnn
import numpy as np

torch.manual_seed(0)
torch.cuda.manual_seed(0)
torch.cuda.manual_seed_all(0)
np.random.seed(0)
cudnn.benchmark = False
cudnn.deterministic = True
random.seed(0)

In [2]:
import torch
import torchvision
import torchvision.transforms as tr
from torch.utils.data import DataLoader

In [3]:
torch.manual_seed(0)

transf = tr.Compose(
    [tr.ToTensor(),
     tr.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

trainset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transf)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=4, shuffle=True, num_workers=2)

testset = torchvision.datasets.CIFAR10(root='./data/', train=False, download=True, transform=transf)
testloader = torch.utils.data.DataLoader(testset, batch_size=4, shuffle=True, num_workers=2)

classes = ('plane', 'car', 'bird', 'cat',
           'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

Files already downloaded and verified
Files already downloaded and verified


In [4]:
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 16 * 5 *5)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x


net = Net()

In [5]:
import torch.optim as optim

criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)

In [6]:
for epoch in range(30):   # 데이터셋을 수차례 반복합니다.

    running_loss = 0.0
    for i, data in enumerate(trainloader, 0):
        # [inputs, labels]의 목록인 data로부터 입력을 받은 후;
        inputs, labels = data

        # 변화도(Gradient) 매개변수를 0으로 만들고
        # 옵티마이저 초기화
        optimizer.zero_grad()

        # 순전파 + 역전파 + 최적화를 한 후
        outputs = net(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        # 통계를 출력합니다.
        running_loss += loss.item()
        if i % 2000 == 1999:    # print every 2000 mini-batches
            print(f'[{epoch + 1}, {i + 1:5d}] loss: {running_loss / 2000:.3f}')
            running_loss = 0.0

print('Finished Training')

[1,  2000] loss: 2.213
[1,  4000] loss: 1.870
[1,  6000] loss: 1.705
[1,  8000] loss: 1.587
[1, 10000] loss: 1.528
[1, 12000] loss: 1.482
[2,  2000] loss: 1.416
[2,  4000] loss: 1.387
[2,  6000] loss: 1.374
[2,  8000] loss: 1.350
[2, 10000] loss: 1.322
[2, 12000] loss: 1.303
[3,  2000] loss: 1.241
[3,  4000] loss: 1.248
[3,  6000] loss: 1.240
[3,  8000] loss: 1.218
[3, 10000] loss: 1.216
[3, 12000] loss: 1.205
[4,  2000] loss: 1.114
[4,  4000] loss: 1.151
[4,  6000] loss: 1.153
[4,  8000] loss: 1.134
[4, 10000] loss: 1.141
[4, 12000] loss: 1.133
[5,  2000] loss: 1.057
[5,  4000] loss: 1.061
[5,  6000] loss: 1.076
[5,  8000] loss: 1.076
[5, 10000] loss: 1.065
[5, 12000] loss: 1.094
[6,  2000] loss: 0.981
[6,  4000] loss: 1.019
[6,  6000] loss: 1.009
[6,  8000] loss: 1.021
[6, 10000] loss: 1.039
[6, 12000] loss: 1.024
[7,  2000] loss: 0.940
[7,  4000] loss: 0.943
[7,  6000] loss: 0.963
[7,  8000] loss: 0.985
[7, 10000] loss: 1.016
[7, 12000] loss: 0.977
[8,  2000] loss: 0.890
[8,  4000] 

In [7]:
PATH = './cifar_net.pth'
torch.save(net.state_dict(), PATH)

In [8]:
net = Net()
net.load_state_dict(torch.load(PATH))

<All keys matched successfully>

In [9]:
_, predicted = torch.max(outputs, 1)

print('Predicted: ', ' '.join(f'{classes[predicted[j]]:5s}'
                              for j in range(4)))

Predicted:  plane truck deer  deer 


In [10]:
correct = 0
total = 0
# 학습 중이 아니므로, 출력에 대한 변화도를 계산할 필요가 없습니다
with torch.no_grad():
    for data in testloader:
        images, labels = data
        # 신경망에 이미지를 통과시켜 출력을 계산합니다
        outputs = net(images)
        # 가장 높은 값(energy)를 갖는 분류(class)를 정답으로 선택하겠습니다
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print(f'Accuracy of the network on the 10000 test images: {100 * correct // total} %')

Accuracy of the network on the 10000 test images: 58 %


In [11]:
# 각 분류(class)에 대한 예측값 계산을 위해 준비
correct_pred = {classname: 0 for classname in classes}
total_pred = {classname: 0 for classname in classes}

# 변화도는 여전히 필요하지 않습니다
with torch.no_grad():
    for data in testloader:
        images, labels = data
        outputs = net(images)
        _, predictions = torch.max(outputs, 1)
        # 각 분류별로 올바른 예측 수를 모읍니다
        for label, prediction in zip(labels, predictions):
            if label == prediction:
                correct_pred[classes[label]] += 1
            total_pred[classes[label]] += 1


# 각 분류별 정확도(accuracy)를 출력합니다
for classname, correct_count in correct_pred.items():
    accuracy = 100 * float(correct_count) / total_pred[classname]
    print(f'Accuracy for class: {classname:5s} is {accuracy:.1f} %')

Accuracy for class: plane is 78.4 %
Accuracy for class: car   is 69.8 %
Accuracy for class: bird  is 48.5 %
Accuracy for class: cat   is 37.1 %
Accuracy for class: deer  is 50.3 %
Accuracy for class: dog   is 52.4 %
Accuracy for class: frog  is 64.9 %
Accuracy for class: horse is 58.2 %
Accuracy for class: ship  is 64.2 %
Accuracy for class: truck is 61.5 %


# MobileNet Code 쳐보면서 궁금한거 만들기

In [1]:
# import package

# model
import torch
import torch.nn as nn
import torch.nn.functional as F
from torchinfo import summary
from torch import optim

# dataset and transformation
from torchvision import datasets
import torchvision.transforms as tr
from torch.utils.data import Dataset, DataLoader
import os

# display images
from torchvision import utils
import matplotlib.pyplot as plt
%matplotlib inline

# utils
import numpy as np
from torchsummary import summary
import time
import copy

# FER Summary
from skimage import io, transform
from torch.utils.tensorboard import SummaryWriter
from PIL import Image
import re
import PIL

# random seed fixed
''' random seed fixed'''
import random
import torch.backends.cudnn as cudnn

path = "/home/sldev1/Project/hyeongeun_test/data/FER"
torch.manual_seed(0)
torch.cuda.manual_seed(0)
torch.cuda.manual_seed_all(0)
np.random.seed(0)
cudnn.benchmark = False
cudnn.deterministic = True
random.seed(0)

In [2]:
from torch.utils.data import Dataset
import glob


def img_load(img_path):

    jpg = glob.glob(img_path+'*.jpg')
    sort_jpg = sorted(jpg, key=lambda s: int(re.findall(r'\d+', s)[1]))
    #print("img_load def is play")
    return sort_jpg


def label_load(label_path):
    #enumerate #파이썬내장함수.. 강민규사원님은 이걸로 쓰셨는데 느리더래
    label = glob.glob(label_path+'*exp.npy')
    sort_label = sorted(label,key=lambda s: int(re.findall(r'\d+', s)[1]))
    #print("label_load def is play")
    return sort_label
    
    
    
class MyFERDataset(Dataset):
    
    def __init__(self, img_path_base, label_path_base, train=None, transform=None):
        super(MyFERDataset, self).__init__()
        
        if train == True:
            self.img_path = img_path_base+'/train_set/images/'
            self.label_path = label_path_base+'/train_set/annotations/'
        else:
            self.img_path = img_path_base+'/val_set/images/'
            self.label_path = label_path_base+'/val_set/annotations/'

        self.img = img_load(self.img_path)
        self.label = label_load(self.label_path)
        self.transform = transform
        
    
    def __getitem__(self, idx):
        img_read = io.imread(self.img[idx]) 
        label_read = np.load(self.label[idx])
        label_read = label_read.astype(np.int64)
        label_tr = torch.from_numpy(label_read)
        
        
        if self.transform:
            img_tr = self.transform(img_read)
        
        
        return img_tr, label_tr
    

    def __len__(self):
        return len(self.label)
    
    if __name__ == "__main__":
        print('hi, i\'m main')

hi, i'm main


In [29]:
# Depthwise Saparable Convolution
class Depthwise(nn.Module):
    def __init__(self, in_channels, out_channels, stride=1):
        super().__init__()
        
        self.depthwise = nn.Sequential(
            nn.Conv2d(in_channels, in_channels, 3, stride=stride, padding=1, groups=in_channels, bias=False),
            # ==> nn.Conv2d(in_channels, out_channels, kernel_size, stride=1, padding=0, dilation=1, groups=1, bias=True, padding_mode='zeros', device=None, dtype=None)
            # ==> kernel size = 3 이란 말은, 3x3을 의미함.
            nn.BatchNorm2d(in_channels),
            nn.ReLU6()
        )
        
        self.pointwise = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, 1, stride=1, padding=0, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU6()
        )

    def forward(self, x):
        x = self.depthwise(x)
        x = self.pointwise(x)
        return x

In [30]:
Depthwise(32, 64)

Depthwise(
  (depthwise): Sequential(
    (0): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=32, bias=False)
    (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU6()
  )
  (pointwise): Sequential(
    (0): Conv2d(32, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
    (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU6()
  )
)

In [31]:
# Basic Conv2d
class BasicConv2d(nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size, **kwargs):
        super().__init__()

        self.conv = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, kernel_size, **kwargs),
            nn.BatchNorm2d(out_channels),
            nn.ReLU()
        )

    def forward(self, x):
        x = self.conv(x)
        return x

# Autograd + backward 연습

In [29]:
import torch
x = torch.tensor(data = [2.0, 3.0], requires_grad=True)
y = x**2
z = 2*y + 3

In [32]:
import torch
x = torch.tensor(data = [2.0, 3.0], requires_grad=True)
y = x**2
z = 2*y + 3

target = torch.tensor([3.0, 4.0])
loss = torch.sum(torch.abs(z-target))
print(z-target)
print(torch.abs(z-target))
print(loss)
loss_2 = torch.abs(z-target)
loss.backward()
print('loss : ',loss)

print('loss_2 : ', loss_2)

print(x.grad, y.grad, z.grad)

tensor([ 8., 17.], grad_fn=<SubBackward0>)
tensor([ 8., 17.], grad_fn=<AbsBackward0>)
tensor(25., grad_fn=<SumBackward0>)
loss :  tensor(25., grad_fn=<SumBackward0>)
loss_2 :  tensor([ 8., 17.], grad_fn=<AbsBackward0>)
tensor([ 8., 12.]) None None


In [33]:
for a in range(10):
    print(a)

print("b")

0
1
2
3
4
5
6
7
8
9
b


# 11/24 목 loss 계산하는 법 탐구 중에 CrossEntropy를 알아야 될 것 같아서 연습

In [2]:
import torch
import torch.nn as nn

In [3]:
loss_func = nn.CrossEntropyLoss()

In [4]:
test_prediction = torch.Tensor([[2, 0.1], [0, 1]])
# 실제 사용에서는 softmax에 의해 각 행의 합이 1이 될 것이다.
print("test_prediction :\n", test_prediction)
print("*********************************")
print(test_prediction.shape) # size
print(test_prediction.type())
type(test_prediction)

test_prediction :
 tensor([[2.0000, 0.1000],
        [0.0000, 1.0000]])
*********************************
torch.Size([2, 2])
torch.FloatTensor


torch.Tensor

In [5]:
test_true_1 = torch.Tensor([1, 0]).long() # 1은 true값이 1번째(클래스)라는 것을 의미
test_true_2 = torch.Tensor([0, 1]).long()

In [6]:
print(test_prediction)
print("*********************************")
print(test_true_1)
print("*********************************")
print(test_true_2)

tensor([[2.0000, 0.1000],
        [0.0000, 1.0000]])
*********************************
tensor([1, 0])
*********************************
tensor([0, 1])


In [8]:
print(loss_func(test_prediction, test_true_1))
print(loss_func(test_prediction, test_true_2))
print((loss_func(test_prediction, test_true_2)+ loss_func(test_prediction, test_true_1)).item())

tensor(1.6763)
tensor(0.2263)
1.9026483297348022


In [25]:
a = torch.tensor([[1,1,1],
                  [1,1,1]])
a.shape

torch.Size([2, 3])

In [1]:
import torch.nn as nn
import torch.optim as optim
from resnet import ResNet18, ResNet34, ResNet50, ResNet101, ResNet152
import os
import torchvision.models as models
from skimage import io, transform
from torch.utils.tensorboard import SummaryWriter



import torch.backends.cudnn as cudnn
import torch
import re
import PIL
import numpy as np
from PIL import Image
from torch.utils.data import Dataset, DataLoader
import torchvision
import torchvision.transforms as tr
from matplotlib import pyplot as plt
import time



######################################################### random seed fixed
import random

path = "/home/sldev1/Project/hyeongeun_test/data/FER"
torch.manual_seed(0)
torch.cuda.manual_seed(0)
torch.cuda.manual_seed_all(0)
np.random.seed(0)
cudnn.benchmark = False
cudnn.deterministic = True
random.seed(0)



########################################################## Simple Learning Rate Scheduler
def lr_scheduler(optimizer, epoch):
    lr = learning_rate
    if epoch == 50:
        lr /= 2
    if epoch == 100:
        lr /= 2
    for param_group in optimizer.param_groups:
        param_group['lr'] = lr

# Xavier
def init_weights(m):
    if isinstance(m, nn.Linear):
        torch.nn.init.xavier_uniform(m.weight)
        m.bias.data.fill_(0.01)
        
        
        
######################################################### 경로 따오고 sort 하는 함수
import glob

def img_load(img_path):

    jpg = glob.glob(img_path+'*.jpg')
    sort_jpg = sorted(jpg, key=lambda s: int(re.findall(r'\d+', s)[1]))
    #print("img_load def is play")
    return sort_jpg


def label_load(label_path):
    #enumerate #파이썬내장함수.. 강민규사원님은 이걸로 쓰셨는데 느리더래
    label = glob.glob(label_path+'*exp.npy')
    sort_label = sorted(label,key=lambda s: int(re.findall(r'\d+', s)[1]))
    #print("label_load def is play")
    return sort_label

In [2]:
from torch.utils.data import Dataset
import glob


def img_load(img_path):

    jpg = glob.glob(img_path+'*.jpg')
    sort_jpg = sorted(jpg, key=lambda s: int(re.findall(r'\d+', s)[1]))
    #print("img_load def is play")
    return sort_jpg


def label_load(label_path):
    #enumerate #파이썬내장함수.. 강민규사원님은 이걸로 쓰셨는데 느리더래
    label = glob.glob(label_path+'*exp.npy')
    sort_label = sorted(label,key=lambda s: int(re.findall(r'\d+', s)[1]))
    #print("label_load def is play")
    return sort_label
    

class MyFERDataset(Dataset):
    
    def __init__(self, img_path_base, label_path_base, train=None, transform=None):
        super(MyFERDataset, self).__init__()
        
        if train == True:
            self.img_path = img_path_base+'/train_set/images/'
            self.label_path = label_path_base+'/train_set/annotations/'
        else:
            self.img_path = img_path_base+'/val_set/images/'
            self.label_path = label_path_base+'/val_set/annotations/'

        self.img = img_load(self.img_path)
        self.label = label_load(self.label_path)
        self.transform = transform
        
    
    def __getitem__(self, idx):
        img_read = io.imread(self.img[idx]) 
        label_read = np.load(self.label[idx])
        label_read = label_read.astype(np.int64)
        label_tr = torch.from_numpy(label_read)
        
        
        if self.transform:
            img_tr = self.transform(img_read)
        
        
        return img_tr, label_tr
    

    def __len__(self):
        return len(self.label)
    
    if __name__ == "__main__":
        print('hi, i\'m main')


hi, i'm main


In [3]:
transform_train = tr.Compose([tr.ToTensor(),
                              tr.Normalize((0.5,0.5,0.5), (0.5,0.5,0.5))])
transform_test = tr.Compose([tr.ToTensor()])


train_dataset = MyFERDataset(img_path_base = path,
                              label_path_base = path,
                              train=True,
                              transform=transform_train)
test_dataset = MyFERDataset(img_path_base = path,
                              label_path_base = path,
                              train=False,
                              transform=transform_test)

In [4]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True, num_workers=2)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False, num_workers=2)

In [5]:
device = 'cuda:0'
model = ResNet50()
# ResNet18, ResNet34, ResNet50, ResNet101, ResNet152 중에 택일하여 사용

In [6]:
model.apply(init_weights)
model = model.to(device)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:52: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.


In [7]:
learning_rate = 0.001
num_epoch = 200
model_name = 'ResNet_FERtest_delete_plz.pth'

loss_fn = nn.CrossEntropyLoss()
# optimizer = optim.SGD(model.parameters(), lr=learning_rate, momentum=0.9, weight_decay=0.0001)
optimizer = optim.Adam(model.parameters(), lr=learning_rate)
train_loss = 0
valid_loss = 0
correct = 0
total_cnt = 0
best_acc = 0

In [11]:
import time
# start = time.time() #시작 시간 저장
# Train
# writer = SummaryWriter("./runs/11.18_loss접근 후 backward+step")
for epoch in range(1):
    
#     if epoch == 0:
#         start = time.time() #시작 시간 저장
#     if epoch == 1:
#         epoch_time_for_1 = time.time()-start
#         timer = epoch_time_for_1 * num_epoch
#         print("학습에 총 걸리는 시간 :", timer)    
    
    

    print(f"====== { epoch+1} epoch of { num_epoch } ======")
    model.train()
    lr_scheduler(optimizer, epoch)
    train_loss = 0
    valid_loss = 0
    correct = 0
    total_cnt = 0
    
    
    
    # Train Phase
    for step, batch in enumerate(test_loader):
        #  input and target
        batch[0], batch[1] = batch[0].to(device), batch[1].to(device)
        optimizer.zero_grad()
        
        print(f"{batch[1]} is batch[1]\n******************batch[1]****************\n")
        print(f"{type(batch[1])} is batch[1]'s type\n****************batch[1]'s type******************\n")
        print(f"{batch[1].shape} is batch[1].shape\n*****************batch[1].shape*****************\n")
        
        logits = model(batch[0]) # 모델에 이미지 집어넣기
        print(f"{logits} is logits\n****************logits************\n")
        print(f"{type(logits)} is logits's type\n***************logits's type*************\n")
        print(f"{logits.shape} is logits's shape\n***************logits's shape*************\n")
        
        loss = loss_fn(logits, batch[1]) # tensor(1.3~~~)이런식으로 나옴.
        # loss.backward()
        # optimizer.step()
        
        train_loss += loss.item()
        #_, predict = logits.max(1)
        _, predict = torch.max(logits, dim=1)
        print(f"{_} is _\n***************_*************\n")
        print(f"{predict} is predict\n**************predict**************\n")
        
        total_cnt += batch[1].size(0)
        correct +=  predict.eq(batch[1]).sum().item()
        
        if step % 1000 == 0 and step != 0:
            print(f"\n====== { step } Step of { len(train_loader) } ======")
            print(f"Train Acc : { correct / total_cnt }")
            print(f"Train Loss : { loss.item() / batch[1].size(0) }")
        
        loss.backward()
        optimizer.step()

            
    train_acc_visual = (correct / total_cnt) * 100
    train_loss_visual = train_loss / batch[1].size(0)
    writer.add_scalar('acc/train', train_acc_visual, epoch)
    writer.add_scalar('loss/train', train_loss_visual, epoch)            
            

    correct = 0
    total_cnt = 0
    
# Test Phase
#     with torch.no_grad():
#         model.eval()
#         for step, batch in enumerate(test_loader):
#             # input and target
#             batch[0], batch[1] = batch[0].to(device), batch[1].to(device)
#             total_cnt += batch[1].size(0)
#             logits = model(batch[0])
#             valid_loss += loss_fn(logits, batch[1])
#             _, predict = logits.max(1)
#             correct += predict.eq(batch[1]).sum().item()
#         valid_acc = correct / total_cnt
#         print(f"\nValid Acc : { valid_acc }")    
#         print(f"Valid Loss : { valid_loss / total_cnt }")
        
#         valid_acc_visual = valid_acc * 100
#         valid_loss_visual = valid_loss / total_cnt
#         writer.add_scalar('acc/valid', valid_acc_visual, epoch)
#         writer.add_scalar('loss/valid', valid_loss_visual, epoch)
        
        

#         if(valid_acc > best_acc):
#             best_acc = valid_acc
#             # torch.save(model, model_name)
#             # print("Model Saved!")
#             torch.save(model.state_dict(), model_name)
#             print('Model Saved!')

====== 1 epoch of 200 ======
tensor([0, 0, 4, 0, 2, 5, 6, 0, 7, 7, 6, 1, 4, 2, 7, 4, 2, 4, 2, 2, 7, 3, 0, 7,
        1, 3, 2, 5, 7, 2, 7, 3], device='cuda:0') is batch[1]
******************batch[1]****************

<class 'torch.Tensor'> is batch[1]'s type
****************batch[1]'s type******************

torch.Size([32]) is batch[1].shape
*****************batch[1].shape*****************

tensor([[ 5.7233e-01,  1.0986e+00,  6.3732e-01,  4.3718e-01,  3.0287e-03,
          8.5802e-01, -3.5717e-02,  1.2701e+00, -4.6271e+00, -3.2598e+00],
        [ 5.8493e-01,  6.8440e-01,  6.3496e-01,  4.4948e-01,  5.2556e-01,
          6.2652e-01,  1.0141e-01,  1.0641e+00, -4.8069e+00, -3.3459e+00],
        [ 4.5936e-01,  8.0601e-02,  8.3221e-01,  4.6567e-01,  1.2426e+00,
          5.9155e-01,  2.9897e-01,  4.8418e-01, -4.9909e+00, -3.4650e+00],
        [ 4.0544e-01,  4.2018e-01,  7.3358e-01,  5.0741e-01,  8.6701e-01,
          6.4301e-01,  2.3439e-01,  6.9178e-01, -4.8304e+00, -3.3644e+00],
        [ 1

KeyboardInterrupt: 